## Get All Product
GET http://localhost:3000/products

### Create Product
POST http://localhost:3000/products

### Get Information of Product id=1
GET http://localhost:3000/products/1


#### No Route
GET http://localhost:3000/about