### Type-1 : Query String
GET http://localhost:3000/test?name=Mac&price=2000

### Type-2 : Route Parameter - 1
GET http://localhost:3000/test/221

### Type-2 : Route Parameter - 2
GET http://localhost:3000/test/2/sumonta

### Type-3 : Request Body
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "Mac",
    "price": 2000
}

### Type-4 : Url Encoded
POST http://localhost:3000/test/urlencoded
Content-Type: application/x-www-form-urlencoded

name=iMac&price=3000

